name: upload-artifacts
on: [push]
jobs:
    Check-Files-Exist:
        uses: ./.github/workflows/validate-themes.yml
    
    Upload-Artifacts:
        runs-on: ubuntu-18.04
        needs: Check-Files-Exist
        steps:
            - name: Checkout 
              uses: actions/checkout@v3
              
            - name: Create a Temporary Directory
              run: mkdir tmp
              
            - name: Compress all Folders into Temp Directory
              run: |
                for dir in ./*/
                do
                    if [[ ${dir} == ./tmp/ ]]
                    then
                        continue
                    fi
                    zip -r ./tmp/theme-${dir:2:${#dir}-3}.zip ${dir}
                done
            
            - name: Upload Archives as Releases
              uses: softprops/action-gh-release@v1
              with:
                name: Themes
                tag_name: Release
                files: tmp/*.zip
