name: output-themes
on: [push, workflow_call]
jobs:
    check-files-exist:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
            - run: python validate.py
      
